SCAME/Controllers/CitasController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SCAME.Data;
using SCAME.Models;

namespace SCAME.Controllers
{
    public class CitasController : Controller
    {
        private readonly ApplicationDbContext _context;
        private UserManager<IdentityUser> userManager;


        public CitasController(ApplicationDbContext context, UserManager<IdentityUser> userMgr)
        {
            _context = context;
            this.userManager = userMgr;
        }

        // GET: Citas
        public async Task<IActionResult> Index()
        {
            var user = await userManager.GetUserAsync(User);
            var listPaciente = await _context.Paciente.Where(p => p.UserId == user.Id).ToListAsync();

            var applicationDbContext = _context.Cita.Include(c => c.Especialidad).Include(c => c.HorasAtencion).Include(c=>c.Medico).Include(c=>c.Consultorio).Include(c => c.Paciente).Where(c=>c.PacienteId == listPaciente[0].IdPaciente);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Citas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cita = await _context.Cita
                .Include(c => c.Especialidad)
                .Include(c => c.HorasAtencion)
                .Include(c => c.Paciente)
                .FirstOrDefaultAsync(m => m.IdCita == id);
            if (cita == null)
            {
                return NotFound();
            }

            return View(cita);
        }

        // GET: Citas/Create
        public IActionResult Create(int idC, int idM,int idE)
        {

            var detalle = _context.MedicoDetalle.Where(d => d.ConsultorioId == idC).ToList();
            ViewData["ConsultorioId"] = idC;
            ViewData["EspecialidadId"] = new SelectList(_context.Especialidad.Where(e=>e.MedicoDetalle.IdMedicoDetalle == detalle[0].IdMedicoDetalle), "Id", "NombreEspecialidad");
            ViewData["MedicoId"] = new SelectList(_context.Medicos.Where(m => m.ConsultorioId == idC), "Id", "Nombre");

            ViewData["HorasAtencionId"] = new SelectList(_context.HorasAtencion.Where(ha => ha.Disponibilidad == true && ha.Turno.ConsultorioId == idC), "IdHorasAtencion", "HoraInicio");
           return View();
           
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FechaCita,MedicoId,MotivoCita,EspecialidadId,ConsultorioId,HorasAtencionId")] Cita cita)
        {
            var user = await userManager.GetUserAsync(User);
            if (ModelState.IsValid)
            {

            
            var listPaciente = await _context.Paciente.Where(p=>p.UserId == user.Id).ToListAsync();
            var horadisponible = await _context.HorasAtencion.Where(h => h.IdHorasAtencion == cita.HorasAtencionId).ToListAsync();

                foreach (var item in listPaciente)
            {
                    
                    cita.PacienteId = item.IdPaciente;
                    cita.EstadoCita = "Activa";
                    cita.Estado = true;
                    _context.Add(cita);
                    horadisponible[0].Disponibilidad = false;
                    _context.Update(horadisponible[0]);
                    await _context.SaveChangesAsync();

                    return RedirectToAction(nameof(Index));
                
                ViewData["EspecialidadId"] = new SelectList(_context.Especialidad, "Id", "Id", cita.EspecialidadId);
                ViewData["HorasAtencionId"] = new SelectList(_context.HorasAtencion, "IdHorasAtencion", "IdHorasAtencion", cita.HorasAtencionId);
                ViewData["PacienteId"] = new SelectList(_context.Paciente, "IdPaciente", "IdPaciente", cita.PacienteId);
                return View(cita);
            }
            }
            return NotFound();
        }

        // GET: Citas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cita = await _context.Cita.FindAsync(id);
            if (cita == null)
            {
                return NotFound();
            }
            ViewData["EspecialidadId"] = new SelectList(_context.Especialidad, "Id", "Id", cita.EspecialidadId);
            ViewData["HorasAtencionId"] = new SelectList(_context.HorasAtencion, "IdHorasAtencion", "IdHorasAtencion", cita.HorasAtencionId);
            ViewData["PacienteId"] = new SelectList(_context.Paciente, "IdPaciente", "IdPaciente", cita.PacienteId);
            return View(cita);
        }

        // POST: Citas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdCita,PacienteId,FechaCita,MedicoId,MotivoCita,MotivoAnulacion,EspecialidadId,ConsultorioId,HorasAtencionId,EstadoCita,Estado")] Cita cita)
        {
            if (id != cita.IdCita)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cita);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CitaExists(cita.IdCita))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EspecialidadId"] = new SelectList(_context.Especialidad, "Id", "Id", cita.EspecialidadId);
            ViewData["HorasAtencionId"] = new SelectList(_context.HorasAtencion, "IdHorasAtencion", "IdHorasAtencion", cita.HorasAtencionId);
            ViewData["PacienteId"] = new SelectList(_context.Paciente, "IdPaciente", "IdPaciente", cita.PacienteId);
            return View(cita);
        }

        // GET: Citas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cita = await _context.Cita
                .Include(c => c.Especialidad)
                .Include(c => c.HorasAtencion)
                .Include(c => c.Paciente)
                .FirstOrDefaultAsync(m => m.IdCita == id);
            if (cita == null)
            {
                return NotFound();
            }

            return View(cita);
        }

        // POST: Citas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cita = await _context.Cita.FindAsync(id);
            _context.Cita.Remove(cita);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CitaExists(int id)
        {
            return _context.Cita.Any(e => e.IdCita == id);
        }
    }
}

SCAME/Controllers/ConsultoriosController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SCAME.Data;
using SCAME.Models;

namespace SCAME.Controllers
{
    public class ConsultoriosController : Controller
    {
        private readonly ApplicationDbContext _context;
        private UserManager<IdentityUser> userManager;
        private readonly IWebHostEnvironment _hostEnvironment;

        public ConsultoriosController(ApplicationDbContext context, UserManager<IdentityUser> userMgr, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            this.userManager = userMgr;
            this._hostEnvironment = hostEnvironment;
        }



        [Authorize(Roles = "Administrador")]
        // GET: Consultorios
        public async Task<IActionResult> Index()
        {
            var applicationDbContext =_context.Consultorio.Include(c => c.Canton).Include(c => c.User).Where(m => m.Estado == true);


            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Consultorios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var consultorio = await _context.Consultorio
                .FirstOrDefaultAsync(m => m.IdConsultorio == id);

            var canton = await _context.Canton.FindAsync(consultorio.CantonId);
            var usuario = await userManager.FindByIdAsync(consultorio.UserId);

            consultorio.Canton = canton;
            consultorio.User = usuario;

            if (consultorio == null)
            {
                return NotFound();
            }

            return View(consultorio);
        }
        [Authorize(Roles = "Usuario, Administrador")]
        // GET: Consultorios/Create
        public IActionResult Create()
        {
            ViewData["CantonId"] = new SelectList(_context.Set<Canton>(), "Id", "NombreCanton");

            return View();
        }

        // POST: Consultorios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Usuario, Administrador")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind ("Ruc, NombreConsultorio, CedulaRepresentanteLegal, NombreRepresentateLegal, ApellidoRepresentanteLegal, Direccion, NumPatenteMunicipal,  PermisoFuncionamientoMsp,  CantonId, ImageFile")] Consultorio consultorio)
        {

            if (ModelState.IsValid)
            {
                var user = await userManager.GetUserAsync(User);

                string wwwRootPath = _hostEnvironment.WebRootPath;
                string fileName = Path.GetFileNameWithoutExtension(consultorio.ImageFile.FileName);
                string extension = Path.GetExtension(consultorio.ImageFile.FileName);
                consultorio.ImageName = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                string path = Path.Combine(wwwRootPath + "/Image/", fileName);

                var fileStream = new FileStream(path, FileMode.Create);
                await consultorio.ImageFile.CopyToAsync(fileStream);


                consultorio.UserId = await userManager.GetUserIdAsync(user);

                var userRol = await userManager.IsInRoleAsync(user, "Usuario");
                if (userRol == true)
                {
                    var eliminarRol = await userManager.RemoveFromRoleAsync(user, "Usuario");
                    var result1 = await userManager.AddToRoleAsync(user, "Consultorio");
                    _context.Add(consultorio);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Create", "Horarios");
                }

            }
            return View();
        }



        [Authorize(Roles = "Consultorio")]
        // GET: Consultorios/Edit/5
        public async Task<IActionResult> Edit()
        {
            var user = await userManager.GetUserAsync(User);
            var id = user.Id;
            if (id == null)
            {
                return NotFound();
            }

            List<Consultorio> listConsultorio = await _context.Consultorio.ToListAsync();
            foreach (var item in listConsultorio)
            {
                if (item.UserId == id)
                {
                    var consultorio = item;

                    if (consultorio == null)
                    {
                        return NotFound();
                    }
                    ViewData["CantonId"] = new SelectList(_context.Set<Canton>(), "Id", "NombreCanton",consultorio.CantonId);

                    return View(consultorio);
                }
            }
            return NotFound();
        }

        // POST: Consultorios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("Ruc,NombreConsultorio,CedulaRepresentanteLegal,NombreRepresentateLegal,ApellidoRepresentanteLegal,Direccion,NumPatenteMunicipal,PermisoFuncionamientoMsp,CantonId,UserId,IdConsultorio,ImageFileNuevo, ImageName")] Consultorio consultorio)
        {
            var user = await userManager.GetUserAsync(User);
            var id = user.Id;
            if (id != consultorio.UserId)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                string wwwRootPath;
                string fileName;
                string extension;
                string path;

                if (consultorio.ImageFileNuevo != null && consultorio.ImageName != null)
                {
                    var imagenPath = Path.Combine(_hostEnvironment.WebRootPath, "Image", consultorio.ImageName);
                    if (System.IO.File.Exists(imagenPath))
                    {
                        System.IO.File.Delete(imagenPath);

                        wwwRootPath = _hostEnvironment.WebRootPath;
                        fileName = Path.GetFileNameWithoutExtension(consultorio.ImageFileNuevo.FileName);
                        extension = Path.GetExtension(consultorio.ImageFileNuevo.FileName);
                        consultorio.ImageName = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                        path = Path.Combine(wwwRootPath + "/Image/", fileName);

                        var fileStream = new FileStream(path, FileMode.Create);
                        await consultorio.ImageFileNuevo.CopyToAsync(fileStream);

                        _context.Update(consultorio);
                        await _context.SaveChangesAsync();
                    }
                }
                wwwRootPath = _hostEnvironment.WebRootPath;
                fileName = Path.GetFileNameWithoutExtension(consultorio.ImageFileNuevo.FileName);
                extension = Path.GetExtension(consultorio.ImageFileNuevo.FileName);
                consultorio.ImageName = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                path = Path.Combine(wwwRootPath + "/Image/", fileName);

                var fileStreamUno = new FileStream(path, FileMode.Create);
                await consultorio.ImageFileNuevo.CopyToAsync(fileStreamUno);

                _context.Update(consultorio);
                await _context.SaveChangesAsync();
                if (!ConsultorioExists(consultorio.IdConsultorio))
                {
                    return NotFound();
                }
                else
                {

                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CantonId"] = new SelectList(_context.Set<Canton>(), "Id", "NombreCanton", consultorio.CantonId);

            return View(consultorio);
        }
        [Authorize(Roles = "Administrador")]
        // GET: Consultorios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var consultorio = await _context.Consultorio
                .FirstOrDefaultAsync(m => m.IdConsultorio == id);
            if (consultorio == null)
            {
                return NotFound();
            }

            return View(consultorio);
        }

        // POST: Consultorios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var consultorio = await _context.Consultorio.FindAsync(id);

            var imagenPath = Path.Combine(_hostEnvironment.WebRootPath, "Image", consultorio.ImageName);
            if (System.IO.File.Exists(imagenPath))
                System.IO.File.Delete(imagenPath);

            consultorio.Estado = false;
            consultorio.ImageName = null;

            var user = await userManager.GetUserAsync(User);
            var userRol = await userManager.IsInRoleAsync(user, "Consultorio");
            if (userRol == true)
            {
                var eliminarRol = await userManager.RemoveFromRoleAsync(user, "Consultorio");
                var agregarRol = await userManager.AddToRoleAsync(user, "Usuario");

            }
            _context.Consultorio.Update(consultorio);
            await _context.SaveChangesAsync();

SCAME/Views/Consultorios/Create.cshtml
@model SCAME.Models.Consultorio

@{
    ViewData["Title"] = "Create";
    List<SelectListItem> items = (List<SelectListItem>)ViewBag.items;
}
 <br />
<div class="container">
  <div class="abs-center">
        <h2>Registro del consultorio</h2>
        <h4>Ingrese todo la información solicitada:</h4>
        <form asp-action="Create" enctype="multipart/form-data"> 
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-row col-md-12">
                        <h4>
                    <div class="form-group col-md-6">
                        <label asp-for="ImageFile" class="control-label"></label>
                        <input asp-for="ImageFile" accept="image/*" />
                        <span asp-validation-for="ImageFile" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-6">
                        <label asp-for="Ruc" class="control-label"></label>
                        <input asp-for="Ruc" class="form-control" />
                        <span asp-validation-for="Ruc" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-6">
                        <label asp-for="NombreConsultorio" class="control-label">Nombre Consultorio</label>
                        <input asp-for="NombreConsultorio" class="form-control" />
                        <span asp-validation-for="NombreConsultorio" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-6">
                    <label asp-for="CedulaRepresentanteLegal" class="control-label">Cédula del representate legal</label>
                    <input asp-for="CedulaRepresentanteLegal" class="form-control" />
                    <span asp-validation-for="CedulaRepresentanteLegal" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="NombreRepresentateLegal" class="control-label">Nombres del representate legal</label>
                    <input asp-for="NombreRepresentateLegal" class="form-control" />
                    <span asp-validation-for="NombreRepresentateLegal" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="ApellidoRepresentanteLegal" class="control-label">Apellidos del representate legal</label>
                    <input asp-for="ApellidoRepresentanteLegal" class="form-control" />
                    <span asp-validation-for="ApellidoRepresentanteLegal" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="CantonId" class="control-label">Selecciona tu ciudad</label>
                    <select asp-for="CantonId" class="form-control" asp-items="ViewBag.CantonId"></select>
                    <span asp-validation-for="CantonId" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="Direccion" class="control-label">Dirección</label>
                    <input asp-for="Direccion" class="form-control" />
                    <span asp-validation-for="Direccion" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="NumPatenteMunicipal" class="control-label">Número de patente municipal</label>
                    <input asp-for="NumPatenteMunicipal" class="form-control" />
                    <span asp-validation-for="NumPatenteMunicipal" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="PermisoFuncionamientoMsp" class="control-label">Número del permiso de funcionamiento otrogado por MSP</label>
                    <input asp-for="PermisoFuncionamientoMsp" class="form-control" />
                    <span asp-validation-for="PermisoFuncionamientoMsp" class="text-danger"></span>
                </div>
                <br>
                <br>
                <div class="form-group col-md-2">
                    <input type="submit" value="Siguiente" class="btn btn-primary" />
                    </div>
                    <div class="form-group col-md-2">
                    <a class="btn btn-primary" asp-area="Identity" asp-page="/Account/Manage/Index">Regresar</a>
                </div>
                </h4>
              </div>
        </form>
         </div>
</div> 

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}

SCAME/Views/Consultorios/Delete.cshtml
@model SCAME.Models.Consultorio

@{
    ViewData["Title"] = "Eliminar";
}

    <div class="col-md-12">
        <h1 class="h1 text-strong text-center padding">Eliminar <small>Consultorio</small></h1>
        <h3>¿Éstas seguro de eliminar? no se podrá recuperar la Información</h3>
        <hr />
        <div>
            <div class="form-row">
                <div class="col-md-1 mb-2">
                    <p class="form-group">Imagen</p>
                    <img src="@("/image/" + Model.ImageName)" asp-append-version="true" width="100px" height="100px" />
                </div>
                <div class="col-md-3 mb-2">
                    <p class="form-group">@Html.DisplayNameFor(model => model.UserId)</p>
                    <label class="form-group">@Html.DisplayFor(model => model.UserId)</label>
                </div>
                <div class="col-md-3 mb-2">
                    <p class="form-group">@Html.DisplayNameFor(model => model.Ruc)</p>
                    <label class="form-group"> @Html.DisplayFor(model => model.Ruc)</label>
                </div>
                <div class="col-md-3 mb-2">
                    <p class="form-group">Nombre del Consultorio</p>
                    <label class="form-group"> @Html.DisplayFor(model => model.NombreConsultorio)</label>
                </div>
            </div>
            <div class="form-row">
                <div class="col-md-1 mb-2"></div>
                <div class="col-md-3 mb-2">
                    <p class="form-group">Cédula del Representante Legal</p>
                    <label class="form-group">@Html.DisplayFor(model => model.CedulaRepresentanteLegal)</label>
                </div>
                <div class="col-md-3 mb-2">
                    <p class="form-group">Nombre del Representate Legal</p>
                    <label class="form-group">
                        @Html.DisplayFor(model => model.NombreRepresentateLegal)
                        @Html.DisplayFor(model => model.ApellidoRepresentanteLegal)
                    </label>
                </div>
                <div class="col-md-3 mb-2">
                    <p class="form-group">@Html.DisplayNameFor(model => model.User.PhoneNumber)</p>
                    <label class="form-group"> @Html.DisplayFor(model => model.User.PhoneNumber)</label>
                </div>

            </div>
            <div class="form-row">
                <div class="col-md-1 mb-2"></div>
                <div class="col-md-3 mb-2">
                    <p class="form-group">@Html.DisplayNameFor(model => model.User.Email)</p>
                    <label class="form-group">@Html.DisplayFor(model => model.User.Email)</label>
                </div>
                <div class="col-md-6 mb-2">
                    <p class="form-group"> Dirección</p>
                    <label class="form-group">@Html.DisplayFor(model => model.Direccion)</label>
                </div>
            </div>
            <div class="form-row">
                <div class="col-md-1 mb-2"></div>
                <div class="col-md-5 mb-2">
                    <p class="form-group">Patente Municipal</p>
                    <label class="form-group">@Html.DisplayFor(model => model.NumPatenteMunicipal)</label>
                </div>
                <div class="col-md-5 mb-2">
                    <p class="form-group">Permiso de Funcionamiento otorgado por el MSP</p>
                    <label class="form-group">@Html.DisplayFor(model => model.PermisoFuncionamientoMsp))</label>
                </div>
            </div>
            <div class="form-row ">
                <div class="form-group col-md-1 mb-3"></div>
                <div class="form-group col-md-2 mb-3">
                    <form asp-action="Delete">
                        <input type="hidden" asp-for="IdConsultorio" />
                        <input type="submit" value="Eliminar" class="btn btn-danger" />
                    </form>
                </div>
                <div class="form-group col-md-6 mb-3"> </div>
                <div class="form-group col-md-2 mb-3">
                    <a class="nav-link" asp-action="Index">Regresar</a>
                </div>
            </div>
            <br />
            <br />

        </div>
    </div>

SCAME/Views/Consultorios/VistaComercial.cshtml
@model IEnumerable<SCAME.Models.Consultorio>
<h6>
    Imagen
</h6>
<img src="@("/Image/" + Model.First().ImageName)" asp-append-version="true" style="width:30px; height:30px" />
<h6>
    @Html.DisplayNameFor(model => model.NombreConsultorio)
</h6>
<h6>
    @Html.DisplayFor(model => model.First().NombreConsultorio)
</h6>
<h6>
    Contacto
</h6>
<h6>
    @Html.DisplayFor(model => model.First().User.PhoneNumber)
</h6>
<h6>
    Correo
</h6>
<h6>
    @Html.DisplayFor(model => model.First().User.Email)
</h6>
<h6>
    @Html.DisplayNameFor(model => model.Direccion)
</h6>
<h6>
    @Html.DisplayFor(model => model.First().Direccion)
</h6>
<table>
    <thead>
        <tr>
            <th>Nombre del especialista</th>
            <th>Especialidad</th>
            <th>Precio</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
<tr>
    <td>@Html.DisplayFor(modelItem => item.Medicos.Apellido) @Html.DisplayFor(model => item.Medicos.Nombre)</td>
    <td>@Html.DisplayFor(modelItem => item.Medicos.Detalle.Especialidad.NombreEspecialidad)</td>
    <td>@Html.DisplayFor(modelItem => item.Medicos.Detalle.PrecioEspecialidad) </td>
    <td>
        <a asp-controller="Citas" asp-action="Create" asp-route-idC="@item.IdConsultorio" asp-route-idM="@item.Medicos.Id" asp-route-idE="@item.Medicos.Detalle.EspecialidadId">Agendar Cita</a>
    </td>
</tr>}
    </tbody>
</table>
@{ }